%% restore_normal_fcs.m
%  Restores Takeoff_FCS to normal takeoff mode (speed controller, mu=0.03)
%  Run this after BFL analysis to go back to normal takeoff simulation.
%  Then run setup_takeoff_fcs.m + press Run in Simulink.
% -----------------------------------------------------------------------
mdl = 'ACFT11_a_121';
if ~bdIsLoaded(mdl), load_system([mdl '.slx']); end

%% Restore 1000 m stop trigger
try
    set_param([mdl '/Alt_1000m_trigger'], 'const', '1000');
    fprintf('[restore] 1000 m stop trigger restored.\n');
catch; end

%% Restore normal FCS code (speed controller, mu=0.03 always)
normal_code = [...
'function [Elevator_deg_cmd, Throttle_cmd, Phase, q_cmd_deg_s, mu_cmd] = Takeoff_FCS(V_mps, BodyRates_radps, EulerAngles_rad, N_total_N, alt_m)' newline ...
'%#codegen' newline ...
'persistent delta_e_prev phase_state q_prev qdot_filt thr_int thr_prev V_filt spd_captured' newline ...
'if isempty(delta_e_prev)' newline ...
'    delta_e_prev=0.0; phase_state=int32(0); q_prev=0.0; qdot_filt=0.0;' newline ...
'    thr_int=1.0; thr_prev=1.0; V_filt=0.0; spd_captured=int32(0);' newline ...
'end' newline ...
'Cm_elev=-0.0084; S=85.25; c=15.55; Iyy=288344.0; rho=1.225;' newline ...
'K_q=5.0; K_theta=1.0; N_filt=15.0; dt=0.02;' newline ...
'V_R=110.0; q_rot_cmd=3.0; theta_clmb=12.0; theta_rot_end=12.0;' newline ...
'N_gear_lo=1000.0; q_max=8.0; de_max=25.0;' newline ...
'V_target=200.0; Kp_V=0.005; Ki_V=0.002; tau_V=1.0; thr_slew=0.10;' newline ...
'q_rps=BodyRates_radps(2); theta_rad=EulerAngles_rad(2);' newline ...
'theta_deg=theta_rad*(180/pi); q_deg=q_rps*(180/pi);' newline ...
'alpha_V=dt/(tau_V+dt);' newline ...
'if V_filt<1.0, V_filt=V_mps; end' newline ...
'V_filt=V_filt+alpha_V*(V_mps-V_filt);' newline ...
'alpha_f=N_filt*dt/(1+N_filt*dt);' newline ...
'qdot_raw=(q_deg-q_prev)/dt;' newline ...
'qdot_filt=(1-alpha_f)*qdot_filt+alpha_f*qdot_raw;' newline ...
'if phase_state==int32(0)' newline ...
'    if V_mps>=V_R, phase_state=int32(1); end' newline ...
'elseif phase_state==int32(1)' newline ...
'    if N_total_N<N_gear_lo||theta_deg>=theta_rot_end, phase_state=int32(2); end' newline ...
'end' newline ...
'if phase_state==int32(0), q_cmd=0.0;' newline ...
'elseif phase_state==int32(1), q_cmd=q_rot_cmd;' newline ...
'else, q_cmd=K_theta*(theta_clmb-theta_deg); q_cmd=max(-q_max,min(q_max,q_cmd)); end' newline ...
'if phase_state==int32(0)' newline ...
'    delta_e_cmd=0.0;' newline ...
'else' newline ...
'    qbar=max(0.5*rho*V_mps^2,0.5*rho*30.0^2);' newline ...
'    G_de=Cm_elev*qbar*S*c/Iyy;' newline ...
'    nu_q=K_q*(q_cmd-q_deg);' newline ...
'    if abs(G_de)>1e-6, Delta_de=(nu_q-qdot_filt)/G_de; else, Delta_de=0.0; end' newline ...
'    delta_e_cmd=delta_e_prev+Delta_de;' newline ...
'    delta_e_cmd=max(-de_max,min(de_max,delta_e_cmd));' newline ...
'end' newline ...
'if phase_state==int32(2)' newline ...
'    if spd_captured==int32(0) && V_filt>=V_target' newline ...
'        spd_captured=int32(1); thr_int=thr_prev;' newline ...
'    end' newline ...
'    if spd_captured==int32(1)' newline ...
'        e_V=V_target-V_filt;' newline ...
'        thr_int=thr_int+Ki_V*e_V*dt; thr_int=max(0.0,min(1.2,thr_int));' newline ...
'        Throttle_raw=max(0.0,min(1.0,Kp_V*e_V+thr_int));' newline ...
'    else' newline ...
'        Throttle_raw=1.0;' newline ...
'    end' newline ...
'else' newline ...
'    Throttle_raw=1.0; spd_captured=int32(0); thr_int=1.0;' newline ...
'end' newline ...
'delta_max=thr_slew*dt;' newline ...
'Throttle_cmd=max(thr_prev-delta_max,min(thr_prev+delta_max,Throttle_raw));' newline ...
'thr_prev=Throttle_cmd;' newline ...
'delta_e_prev=delta_e_cmd; q_prev=q_deg;' newline ...
'Elevator_deg_cmd=delta_e_cmd;' newline ...
'Phase=double(phase_state); q_cmd_deg_s=q_cmd;' newline ...
'mu_cmd=0.03;' newline ...
'end'];

rt = sfroot;
charts = rt.find('-isa','Stateflow.EMChart');
for k = 1:numel(charts)
    if contains(charts(k).Path, [mdl '/Takeoff_FCS'])
        charts(k).Script = normal_code;
        break;
    end
end

set_param(mdl, 'StopTime', '130');
save_system(mdl);
fprintf('[restore] Normal FCS restored. Run setup_takeoff_fcs.m + Simulink Run.\n');
