%% setup_bfl_analysis.m
%  Balanced Field Length (BFL) — Engine-out takeoff simulation setup.
%
%  AIRCRAFT  : 2 × 70 kN = 140 kN total thrust
%  OBSTACLE  : 35 ft (10.668 m) screen height
%  BFL       : V1 where [accelerate-go distance] = [accelerate-stop distance]
%
%  ┌─────────────────────────────────────────────────────────────────────┐
%  │ USAGE                                                               │
%  │  1) Set V1_mps and SCENARIO below.                                  │
%  │  2) Run this script.                                                │
%  │  3) Press Run in Simulink.                                          │
%  │  4) Run analyze_bfl.m for results.                                  │
%  │  5) To find the balanced V1, use run_bfl_sweep.m                    │
%  └─────────────────────────────────────────────────────────────────────┘
%
%  FCS PHASES (BFL mode):
%    Phase  0  GROUND_ROLL   — both engines (Throttle=1.0), μ=0.03
%    Phase  1  OEI_ROLL      — one engine (Throttle=0.5), μ=0.03, roll to VR
%    Phase  2  ROTATION_OEI  — one engine, INDI q_cmd=3 deg/s
%    Phase  3  CLIMB_OEI     — one engine, θ_cmd=12°, until 35 ft cleared
%    Phase 10  BRAKING       — idle (Throttle=0.05), μ=0.3, decelerate to stop
%
%  Engine-out modelled as: remaining engine at full = 50% of total thrust.
%  Full-brakes modelled as: μ_brake=0.3 vs μ_roll=0.03.
% -----------------------------------------------------------------------

mdl = 'ACFT11_a_121';

%% ===========================  USER PARAMETERS  ===========================
V1_mps   = 95.2;    % m/s  decision speed (V1).  Valid range: 70–108 m/s
                  %      (must be < VR = 110 m/s)
SCENARIO = 1;     % 1 = GO   : engine fails at V1, continue, rotate, clear 35 ft
                  % 0 = STOP : engine fails at V1, max braking to full stop
%% =========================================================================

if V1_mps >= 110
    error('V1_mps (%g) must be less than VR = 110 m/s.', V1_mps);
end

%% ---- Load model ---------------------------------------------------------
if ~bdIsLoaded(mdl)
    load_system([mdl '.slx']);
    fprintf('[bfl] Model loaded.\n');
else
    fprintf('[bfl] Model already open.\n');
end

%% ---- Workspace variables (same aero/inertia as normal takeoff) ----------
Mass    = 28500;  g = 9.80665;  Mass_kg = Mass;
Ixx = 74848;   Iyy = 288344;   Izz = 390125;   Ixz = 2511;
Inertia = [Ixx 0 -Ixz; 0 Iyy 0; -Ixz 0 Izz];
Ixx1=32379; Iyy1=136386; Izz1=168765; Ixz1=2511;
InertiaEmpty = [Ixx1 0 -Ixz1; 0 Iyy1 0; -Ixz1 0 Izz1];
y_cg=0; z_cg=0; Xcg=9.87;
V_reference_mps=200; rho_reference_kgpm3=1.225; nv=0; nrho=0.75;
alfaf_deg=-1.8; xf_m=0; zf_m=-0.08; Tmax=140000;
S=85.25; c=15.55; b=9.05;
CL0=0.00003;  CL_alpha=-0.247; CL_elev=0.0179; CL_AlphaDot=0; CL_q=-0.114;
CD0=0.00554;  CD_alpha=0.0177; CD_elev=0.0001;
CY_beta=0.0228; CY_rud=0; CY_ail=0.00327; CY_r=0.105; CY_p=0.0305;
Cl_beta=0.0393; Cl_rud=0; Cl_ail=-0.00325; Cl_r=-0.035; Cl_p=-0.00065;
Cm0=0.00007; Cm_alpha=-0.124; Cm_elev=-0.0084; Cm_AlphaDot=0; Cm_q=-0.025;
Cn_beta=-0.0123; Cn_rud=0; Cn_ail=-0.00194; Cn_r=0.0168; Cn_p=-0.0185;
Lgrfrontx=1.92; Lgrfronty=0; Lgrfrontz=0.5;

vars = {'Mass','g','Mass_kg','Ixx','Iyy','Izz','Ixz','Inertia', ...
        'Ixx1','Iyy1','Izz1','Ixz1','InertiaEmpty', ...
        'y_cg','z_cg','Xcg','V_reference_mps','rho_reference_kgpm3', ...
        'nv','nrho','alfaf_deg','xf_m','zf_m','Tmax', ...
        'S','c','b', ...
        'CL0','CL_alpha','CL_elev','CL_AlphaDot','CL_q', ...
        'CD0','CD_alpha','CD_elev', ...
        'CY_beta','CY_rud','CY_ail','CY_r','CY_p', ...
        'Cl_beta','Cl_rud','Cl_ail','Cl_r','Cl_p', ...
        'Cm0','Cm_alpha','Cm_elev','Cm_AlphaDot','Cm_q', ...
        'Cn_beta','Cn_rud','Cn_ail','Cn_r','Cn_p', ...
        'Lgrfrontx','Lgrfronty','Lgrfrontz'};
for k = 1:numel(vars)
    assignin('base', vars{k}, eval(vars{k}));
end
fprintf('[bfl] %d workspace variables loaded.\n', numel(vars));

%% ---- Initial conditions -------------------------------------------------
set_param([mdl '/EqM/InertialData/ZI_m'],    'InitialCondition','-2.23952');
set_param([mdl '/EqM/EulerAngles/THETA_rad'],'InitialCondition','2*pi/180');
set_param([mdl '/EqM/BodyVelocities/u_mps'], 'InitialCondition','0');
set_param([mdl '/EqM/BodyVelocities/v_mps'], 'InitialCondition','0');
set_param([mdl '/EqM/BodyVelocities/w_mps'], 'InitialCondition','0');

%% ---- Solver (longer time for braking scenarios) -------------------------
set_param(mdl, 'StopTime',          '150');
set_param(mdl, 'SolverName',        'ode15s');
set_param(mdl, 'SolverType',        'Variable-step');
set_param(mdl, 'RelTol',            '1e-3');
set_param(mdl, 'AbsTol',            '1e-4');
set_param(mdl, 'MaxStep',           '0.05');
set_param(mdl, 'AlgebraicLoopMsg', 'none');
set_param(mdl, 'ReturnWorkspaceOutputs', 'off');
set_param(mdl, 'LoadExternalInput', 'off');

%% ---- Bypass the 1000 m stop trigger (BFL won't reach 1000 m) -----------
try
    set_param([mdl '/Alt_1000m_trigger'], 'const', '9999');
    fprintf('[bfl] 1000 m stop trigger bypassed (set to 9999 m).\n');
catch
    fprintf('[bfl] Note: could not bypass 1000 m stop block — ignored.\n');
end

%% ---- Inject BFL FCS code with V1 and scenario --------------------------
bfl_go = double(SCENARIO == 1);
bfl_code = make_bfl_fcs_code(V1_mps, bfl_go);

rt = sfroot;
charts = rt.find('-isa','Stateflow.EMChart');
fcs_found = false;
for k = 1:numel(charts)
    if contains(charts(k).Path, [mdl '/Takeoff_FCS'])
        charts(k).Script = bfl_code;
        fcs_found = true;
        break;
    end
end
if ~fcs_found, error('[bfl] Takeoff_FCS not found in model.'); end
fprintf('[bfl] BFL FCS injected:  V1=%.1f m/s  Scenario=%s\n', ...
    V1_mps, ternary(SCENARIO==1,'GO (continue)','STOP (brake)'));

save_system(mdl);
fprintf('[bfl] Model saved.\n');

%% ---- Summary -----------------------------------------------------------
W  = Mass * g;
T1 = Tmax * 0.5;   % one engine
fprintf('\n');
fprintf('==============================================================\n');
fprintf('  BFL SIMULATION READY\n');
fprintf('  Aircraft   : Mass=%g kg  T_both=%g kN  T_one=%.0f kN\n', Mass, Tmax/1e3, T1/1e3);
fprintf('  T/W (2eng) : %.2f     T/W (1eng): %.2f\n', Tmax/W, T1/W);
fprintf('  V1         : %.1f m/s  (%.1f kt)\n', V1_mps, V1_mps/0.51444);
fprintf('  VR         : 110.0 m/s (%.1f kt)\n', 110/0.51444);
fprintf('  Obstacle   : 35 ft = 10.668 m\n');
fprintf('  Scenario   : %s\n', ternary(SCENARIO==1,...
    'GO  — engine out at V1, rotate at VR, clear 35 ft',...
    'STOP — engine out at V1, full brakes (μ=0.3), stop'));
fprintf('  FCS phases : 0=GndRoll | 1=OEI Roll | 2=Rotation | 3=Climb | 10=Braking\n');
fprintf('  Sim time   : 150 s\n');
fprintf('==============================================================\n');
fprintf('\n  --> Press RUN in Simulink.\n');
fprintf('      Then run analyze_bfl.m for BFL distances.\n');
fprintf('\n  To find balanced V1, run run_bfl_sweep.m (automated).\n\n');

%% =========================================================================
%  RESTORE function — call after BFL to go back to normal takeoff mode
%% =========================================================================
% restore_normal_fcs(mdl)   % uncomment if needed

%% =========================================================================
%  LOCAL FUNCTIONS
%% =========================================================================

function out = ternary(cond, a, b)
    if cond, out = a; else, out = b; end
end

function code = make_bfl_fcs_code(V1, go_flag)
%MAKE_BFL_FCS_CODE  Generate BFL FCS with engine-out phases.
%  go_flag: 1 = continue (GO)  |  0 = brake and stop (STOP)

code = sprintf([...
'function [Elevator_deg_cmd, Throttle_cmd, Phase, q_cmd_deg_s, mu_cmd] = Takeoff_FCS(V_mps, BodyRates_radps, EulerAngles_rad, N_total_N, alt_m)\n'...
'%%#codegen\n'...
'%% BFL: Phase 0=GndRoll(2eng) | 1=OEI Roll | 2=ROT_OEI | 3=CLM_OEI | 10=BRAKING\n'...
'persistent delta_e_prev phase_state q_prev qdot_filt thr_prev V_filt\n'...
'if isempty(delta_e_prev)\n'...
'    delta_e_prev=0.0; phase_state=int32(0); q_prev=0.0; qdot_filt=0.0;\n'...
'    thr_prev=1.0; V_filt=0.0;\n'...
'end\n'...
'%% --- BFL parameters (injected by setup_bfl_analysis.m) ---\n'...
'V1_mps  = %.4f;  %% m/s  decision speed\n'...
'BFL_GO  = %d;    %% 1=GO (continue), 0=STOP (brake)\n'...
'%% --- Aircraft constants ---\n'...
'Cm_elev=-0.0084; S=85.25; c=15.55; Iyy=288344.0; rho=1.225;\n'...
'K_q=5.0; K_theta=1.0; N_filt=15.0; dt=0.02;\n'...
'V_R=110.0; q_rot_cmd=3.0; theta_clmb=12.0; theta_rot_end=12.0;\n'...
'N_gear_lo=1000.0; q_max=8.0; de_max=25.0; tau_V=1.0;\n'...
'%% --- State extraction ---\n'...
'q_rps=BodyRates_radps(2); theta_rad=EulerAngles_rad(2);\n'...
'theta_deg=theta_rad*(180/pi); q_deg=q_rps*(180/pi);\n'...
'alpha_V=dt/(tau_V+dt);\n'...
'if V_filt<1.0, V_filt=V_mps; end\n'...
'V_filt=V_filt+alpha_V*(V_mps-V_filt);\n'...
'alpha_f=N_filt*dt/(1+N_filt*dt);\n'...
'qdot_raw=(q_deg-q_prev)/dt;\n'...
'qdot_filt=(1-alpha_f)*qdot_filt+alpha_f*qdot_raw;\n'...
'%% --- Phase state machine ---\n'...
'if phase_state==int32(0)\n'...
'    if V_mps>=V1_mps\n'...
'        if BFL_GO==1, phase_state=int32(1);\n'...
'        else,         phase_state=int32(10); end\n'...
'    end\n'...
'elseif phase_state==int32(1)\n'...
'    if V_mps>=V_R, phase_state=int32(2); end\n'...
'elseif phase_state==int32(2)\n'...
'    if N_total_N<N_gear_lo||theta_deg>=theta_rot_end, phase_state=int32(3); end\n'...
'end\n'...
'%% --- q command ---\n'...
'if phase_state<=int32(1), q_cmd=0.0;\n'...
'elseif phase_state==int32(2), q_cmd=q_rot_cmd;\n'...
'elseif phase_state==int32(3)\n'...
'    q_cmd=K_theta*(theta_clmb-theta_deg); q_cmd=max(-q_max,min(q_max,q_cmd));\n'...
'else, q_cmd=0.0; end\n'...
'%% --- INDI elevator ---\n'...
'if phase_state==int32(0)||phase_state==int32(10)\n'...
'    delta_e_cmd=0.0;\n'...
'else\n'...
'    qbar=max(0.5*rho*V_mps^2,0.5*rho*30.0^2);\n'...
'    G_de=Cm_elev*qbar*S*c/Iyy;\n'...
'    nu_q=K_q*(q_cmd-q_deg);\n'...
'    if abs(G_de)>1e-6, Delta_de=(nu_q-qdot_filt)/G_de; else, Delta_de=0.0; end\n'...
'    delta_e_cmd=delta_e_prev+Delta_de;\n'...
'    delta_e_cmd=max(-de_max,min(de_max,delta_e_cmd));\n'...
'end\n'...
'%% --- Throttle: 1.0 both engines | 0.5 OEI full | 0.05 idle(brake) ---\n'...
'if phase_state==int32(0),  Throttle_cmd=1.0;\n'...
'elseif phase_state==int32(10), Throttle_cmd=0.05;\n'...
'else,  Throttle_cmd=0.5; end\n'...
'thr_prev=Throttle_cmd;\n'...
'%% --- mu_cmd: rolling=0.03, full brakes=0.3 ---\n'...
'if phase_state==int32(10), mu_cmd=0.3;\n'...
'else, mu_cmd=0.03; end\n'...
'%% --- State update ---\n'...
'delta_e_prev=delta_e_cmd; q_prev=q_deg;\n'...
'Elevator_deg_cmd=delta_e_cmd;\n'...
'Phase=double(phase_state); q_cmd_deg_s=q_cmd;\n'...
'end\n'], V1, go_flag);
end
